version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment: 
      - MARIADB_ROOT_PASSWORD=P@ssw0rd
      - MARIADB_DATABASE=Admin
    ports: 
      - 3306:3306


